
# 服务名称
spring:
  application:
    name: cs-spring-cloud-eureka
# 服务端口号
server:
  port: 9999

eureka:
  instance:
    hostname: eureka-center
    appname: zhuce-zhongxin
  client:
    registerWithEureka: false # 单点的时候设置为 false 禁止注册自身
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9999/eureka
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000
#Eureka 相关配置
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:${server.port}/eureka/
#    # 是否从其他的服务中心同步服务列表
#    fetch-registry: false
#    # 是否把自己作为服务注册到其他服务注册中心
#    register-with-eureka: false
